export const parentLibraryCategories = [
  {
    slug: "understanding-autism",
    title: "Understanding Autism",
    articles: [
      "What autism is",
      "Autism across ages",
      "Communication differences",
      "Sensory differences",
      "Meltdowns vs tantrums",
      "Executive functioning",
      "Routines and predictability",
      "Strength-based support",
      "Respectful language",
      "Supporting teens and adults with dignity",
    ],
  },
  {
    slug: "communication-support",
    title: "Communication Support",
    articles: [
      "Wait-and-watch exercise",
      "Offer two choices exercise",
      "Model without forcing speech",
      "Use AAC during daily routines",
      "Build a phrase board",
      "Practice yes/no",
      "Practice help, break, stop, and I need space",
      "Use visuals before transitions",
      "Reduce question overload",
      "Create communication opportunities across daily contexts",
    ],
  },
  {
    slug: "daily-living-skills",
    title: "Daily Living Skills",
    articles: [
      "Brushing teeth",
      "Washing hands",
      "Getting dressed",
      "Packing a bag",
      "Cleaning up",
      "Making a simple snack",
      "Morning routine",
      "Bedtime routine",
      "Shower routine",
      "Laundry basics",
      "Money basics",
      "Time management",
      "Community safety",
      "Job readiness for teens and adults",
    ],
  },
  {
    slug: "emotional-regulation",
    title: "Emotional Regulation",
    articles: [
      "Emotion labeling",
      "Body signals",
      "Calm-down menu",
      "Breathing practice",
      "First calm, then solve",
      "Safe break routine",
      "Heavy work and movement breaks",
      "Sensory toolkit planning",
      "After-meltdown recovery",
      "Repair conversation",
      "Choosing coping tools",
    ],
  },
  {
    slug: "sensory-support",
    title: "Sensory Support",
    articles: [
      "Sensory profile guide",
      "Noise sensitivity tools",
      "Clothing sensitivity tools",
      "Food texture support",
      "Transition support",
      "Visual clutter reduction",
      "Calm space setup",
      "Movement breaks",
      "Deep pressure safety notes",
      "Sensory diet planner",
      "What to track before judging behavior",
    ],
  },
  {
    slug: "behavior-support",
    title: "Behavior Support",
    articles: [
      "Find the reason behind behavior",
      "Track triggers with ABC logs",
      "Replacement skills",
      "Prevent overload",
      "Offer choices",
      "Use visual schedules",
      "Teach break before escalation",
      "Reinforce communication",
      "Avoid shame language",
      "Avoid forcing eye contact",
      "Avoid compliance-only design",
    ],
  },
  {
    slug: "social-stories",
    title: "Social Stories Library",
    articles: [
      "Going to school",
      "Going to work",
      "Doctor visit",
      "Dentist visit",
      "Haircut",
      "Trying new food",
      "Loud places",
      "Sharing space",
      "Waiting",
      "Taking turns",
      "Riding in the car",
      "Going to the store",
      "Meeting new people",
      "When plans change",
      "Asking for help",
      "Saying no",
      "Personal boundaries",
      "Internet safety",
      "Public bathroom safety",
    ],
  },
  {
    slug: "parent-coaching-plans",
    title: "Parent Coaching Plans",
    articles: [
      "7-day communication boost",
      "7-day morning routine builder",
      "14-day toilet routine support",
      "14-day emotional regulation plan",
      "30-day independence plan",
      "30-day teen and adult life skills plan",
    ],
  },
  {
    slug: "crisis-overload-support",
    title: "Crisis and Overload Support",
    articles: [
      "Early warning signs",
      "What to do during overload",
      "What not to do",
      "How to reduce demands",
      "How to keep everyone safe",
      "Recovery steps",
      "When to contact a professional",
      "Emergency contact planning",
    ],
  },
] as const;
