export type BridgePetProfile = {
  slug: string;
  name: string;
  descriptor: string;
  about: string;
  audienceTags: string[];
  supportTags: string[];
  personalityTraits: string[];
  primaryColor: string;
  accentColor: string;
  palette: string[];
  cardImage?: string;
  spriteImage?: string;
  boardImage?: string;
  badgeImages: string[];
  iconImages: string[];
  poses: string[];
  outfits: string[];
  expressions: string[];
};

const base = "/assets/bridge-pets/bridge_pets_codex_asset_pack";
const card = (slug: string) => `${base}/characters/cards_png/${slug}_card.png`;
const sprite = (slug: string) => `${base}/characters/main_sprite_crops_png/${slug}_main_sprite_crop.png`;
const board = (file: string) => `${base}/boards/png/${file}`;
const badge = (file: string) => `${base}/graphics/badges_png/${file}`;
const icon = (file: string) => `${base}/graphics/icons/png/${file}`;

const sharedPoses = ["Idle", "Wave", "Listening", "Thinking", "Cheering", "Check-in"];
const sharedOutfits = ["Default", "Hoodie", "Headphones", "Explorer", "Calm", "Focused"];
const sharedExpressions = ["Neutral", "Happy", "Focused", "Sleepy", "Proud"];

export const bridgePetProfiles: BridgePetProfile[] = [
  {
    slug: "spark",
    name: "Spark",
    descriptor: "Your energized motivation companion.",
    about: "Spark helps turn small starts into momentum with bright, habit-building encouragement.",
    audienceTags: ["Teens", "Adults", "Routine support"],
    supportTags: ["Routine support", "Ready-for-action"],
    personalityTraits: ["motivated", "positive", "habit-building"],
    primaryColor: "#FFD400",
    accentColor: "#906AFF",
    palette: ["#FFD400", "#FFC737", "#6A3DFF", "#1A1630", "#FFE6A3", "#FF6AD1"],
    boardImage: board("spark_reference_original.png"),
    badgeImages: [badge("routine_support_badge.png"), badge("ready_for_action_badge.png")],
    iconImages: [icon("routine_support.png"), icon("growth_progress.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "tide",
    name: "Tide",
    descriptor: "Your calming companion. Always steady. Always flowing.",
    about: "Tide supports regulation, reset, and calmer transitions when the day feels big.",
    audienceTags: ["Teens", "Adults", "Calm support"],
    supportTags: ["Calm support"],
    personalityTraits: ["calming", "steady", "emotional regulation"],
    primaryColor: "#21B7FF",
    accentColor: "#7CE6FF",
    palette: ["#081024", "#12204A", "#1E3FAE", "#21B7FF", "#7CE6FF", "#A48CFF", "#FFE6DB"],
    boardImage: board("tide_asset_board.png"),
    badgeImages: [badge("calm_support_badge.png")],
    iconImages: [icon("calm_support.png"), icon("privacy_secure.png")],
    poses: sharedPoses,
    outfits: ["Default", "Rain hoodie", "Headphones", "Explorer", "Calm", "Focused"],
    expressions: sharedExpressions,
  },
  {
    slug: "nova",
    name: "Nova",
    descriptor: "Your curious companion. Always exploring. Always expanding.",
    about: "Nova encourages creativity, exploration, and expressive problem-solving.",
    audienceTags: ["Teens", "Creative expression"],
    supportTags: ["Creative expression"],
    personalityTraits: ["curious", "creative", "uplifting"],
    primaryColor: "#9D7BFF",
    accentColor: "#79F0FF",
    palette: ["#9D7BFF", "#6A4DFF", "#3A28CC", "#16132E", "#FFE69B", "#79F0FF", "#FF6DF4"],
    boardImage: board("nova_asset_board.png"),
    badgeImages: [badge("creative_expression_badge.png"), badge("teens_badge.png")],
    iconImages: [icon("creative_expression.png"), icon("teens.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "moss",
    name: "Moss",
    descriptor: "Your grounded companion. Always rooted. Always growing.",
    about: "Moss helps slow things down, build routines, and stay centered through steady practice.",
    audienceTags: ["Calm support", "Routine support"],
    supportTags: ["Calm support", "Routine support"],
    personalityTraits: ["grounded", "patient", "routine-building"],
    primaryColor: "#6BAF6E",
    accentColor: "#8ED28A",
    palette: ["#6BAF6E", "#8ED28A", "#BFE8A9", "#4A7F4A", "#2E4A30", "#3D2E1F", "#FF6FB7"],
    boardImage: board("moss_asset_board.png"),
    badgeImages: [badge("calm_support_badge.png"), badge("routine_support_badge.png")],
    iconImages: [icon("calm_support.png"), icon("routine_support.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "bolt",
    name: "Bolt",
    descriptor: "Your bold momentum companion.",
    about: "Bolt brings upbeat energy for action, follow-through, and movement-friendly motivation.",
    audienceTags: ["Routine support", "Ready-for-action"],
    supportTags: ["Routine support", "Ready-for-action"],
    personalityTraits: ["energetic", "action-driven", "motivating"],
    primaryColor: "#FFD400",
    accentColor: "#6A3DFF",
    palette: ["#6A3DFF", "#906AFF", "#FFD400", "#FFC737", "#1A1630", "#0D0B1A", "#FF6AD1"],
    boardImage: board("bolt_asset_board.png"),
    badgeImages: [badge("ready_for_action_badge.png"), badge("routine_support_badge.png")],
    iconImages: [icon("ready_for_action.png"), icon("routine_support.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "ranger",
    name: "Ranger",
    descriptor: "Your steady purpose companion.",
    about: "Ranger supports resilience, purpose, and steady routines without combat themes or official insignia.",
    audienceTags: ["Ready-for-action", "Adults", "Teens"],
    supportTags: ["Ready-for-action", "Routine support"],
    personalityTraits: ["resilient", "mission-focused", "ready-for-action", "purpose-driven"],
    primaryColor: "#87D65A",
    accentColor: "#C58A4A",
    palette: ["#87D65A", "#3C4F2F", "#C58A4A", "#171B12"],
    cardImage: card("ranger"),
    spriteImage: sprite("ranger"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("ready_for_action_badge.png"), badge("adults_badge.png")],
    iconImages: [icon("ready_for_action.png"), icon("privacy_secure.png")],
    poses: sharedPoses,
    outfits: ["Default", "Resilience jacket", "Explorer", "Calm", "Focused"],
    expressions: sharedExpressions,
  },
  {
    slug: "focus",
    name: "Focus",
    descriptor: "Built for clarity and momentum.",
    about: "Focus supports attention, organization, and productive next steps for users who need clarity.",
    audienceTags: ["Focus support", "Routine support"],
    supportTags: ["Focus support", "Routine support"],
    personalityTraits: ["organized", "clear", "productive", "attention-supportive"],
    primaryColor: "#20C7FF",
    accentColor: "#8DFF5A",
    palette: ["#20C7FF", "#8DFF5A", "#0B2030", "#EAFBFF"],
    cardImage: card("focus"),
    spriteImage: sprite("focus"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("focus_support_badge.png"), badge("routine_support_badge.png")],
    iconImages: [icon("focus_support.png"), icon("routine_support.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "zip",
    name: "Zip",
    descriptor: "For busy minds and bold moves.",
    about: "Zip supports momentum, routines, and playful energy for fast-thinking days.",
    audienceTags: ["Focus support", "Routine support", "Teens"],
    supportTags: ["Focus support", "Routine support"],
    personalityTraits: ["fast-thinking", "playful", "momentum-building", "busy-mind friendly"],
    primaryColor: "#FF8A20",
    accentColor: "#00C9CF",
    palette: ["#FF8A20", "#00C9CF", "#111827", "#FFD15A"],
    cardImage: card("zip"),
    spriteImage: sprite("zip"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("focus_support_badge.png"), badge("routine_support_badge.png"), badge("teens_badge.png")],
    iconImages: [icon("focus_support.png"), icon("routine_support.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "echo",
    name: "Echo",
    descriptor: "Always connected. Always expressive.",
    about: "Echo supports self-expression, social confidence, music, creativity, and teen-friendly identity.",
    audienceTags: ["Teens", "Creative expression"],
    supportTags: ["Creative expression"],
    personalityTraits: ["expressive", "social", "creative", "teen-friendly"],
    primaryColor: "#A15CFF",
    accentColor: "#1DD3FF",
    palette: ["#A15CFF", "#1DD3FF", "#2D1747", "#F069FF"],
    cardImage: card("echo"),
    spriteImage: sprite("echo"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("creative_expression_badge.png"), badge("teens_badge.png")],
    iconImages: [icon("creative_expression.png"), icon("teens.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "atlas",
    name: "Atlas",
    descriptor: "Built for goals, balance, and progress.",
    about: "Atlas supports adult goals, life structure, balance, and long-view progress.",
    audienceTags: ["Adults", "Routine support"],
    supportTags: ["Routine support"],
    personalityTraits: ["structured", "balanced", "goal-focused", "adult-friendly"],
    primaryColor: "#FFC34A",
    accentColor: "#F3E6BF",
    palette: ["#FFC34A", "#222329", "#0A0B12", "#F3E6BF"],
    cardImage: card("atlas"),
    spriteImage: sprite("atlas"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("adults_badge.png"), badge("routine_support_badge.png")],
    iconImages: [icon("adults.png"), icon("growth_progress.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "luna",
    name: "Luna",
    descriptor: "Gentle support for reset and reflection.",
    about: "Luna supports calm resets, reflection, emotional regulation, and soft encouragement.",
    audienceTags: ["Calm support", "Teens", "Adults"],
    supportTags: ["Calm support"],
    personalityTraits: ["soothing", "reflective", "calming", "reset-focused"],
    primaryColor: "#C89CFF",
    accentColor: "#7F5BFF",
    palette: ["#C89CFF", "#7F5BFF", "#17102A", "#FFE6FF"],
    cardImage: card("luna"),
    spriteImage: sprite("luna"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("calm_support_badge.png"), badge("adults_badge.png")],
    iconImages: [icon("calm_support.png"), icon("privacy_secure.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "rocket",
    name: "Rocket",
    descriptor: "Fuel for action and follow-through.",
    about: "Rocket brings active energy for movement, rewards, and getting back into motion.",
    audienceTags: ["Routine support", "Ready-for-action"],
    supportTags: ["Routine support", "Ready-for-action"],
    personalityTraits: ["active", "energetic", "follow-through focused"],
    primaryColor: "#FF3D31",
    accentColor: "#FFBE2E",
    palette: ["#FF3D31", "#FFBE2E", "#311111", "#FFE1D1"],
    cardImage: card("rocket"),
    spriteImage: sprite("rocket"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("routine_support_badge.png"), badge("ready_for_action_badge.png")],
    iconImages: [icon("routine_support.png"), icon("ready_for_action.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
  {
    slug: "sage",
    name: "Sage",
    descriptor: "A calm guide for everyday growth.",
    about: "Sage supports reassurance, wise planning, and steady growth for adults and older users.",
    audienceTags: ["Adults", "Calm support"],
    supportTags: ["Calm support", "Routine support"],
    personalityTraits: ["wise", "reassuring", "steady", "adult-growth focused"],
    primaryColor: "#8ED28A",
    accentColor: "#C8D6B0",
    palette: ["#8ED28A", "#2E4A30", "#C8D6B0", "#101810"],
    cardImage: card("sage"),
    spriteImage: sprite("sage"),
    boardImage: board("eight_character_lineup.png"),
    badgeImages: [badge("adults_badge.png"), badge("calm_support_badge.png")],
    iconImages: [icon("adults.png"), icon("calm_support.png")],
    poses: sharedPoses,
    outfits: sharedOutfits,
    expressions: sharedExpressions,
  },
];

export function getBridgePetProfile(slug: string) {
  return bridgePetProfiles.find((pet) => pet.slug === slug) ?? null;
}
